from typing import List, Tuple, Optional
from dataclasses import dataclass
import math


@dataclass
class Point:
    x: float
    y: float


class GCodeGenerator:
    """Generates standard G-code commands for the plotter"""

    def __init__(
        self,
        pen_up_cmd: str = "M5",
        pen_down_cmd: str = "M3 S90",
        feed_rate: int = 1000,
        rapid_rate: int = 3000,
        units: str = "mm",
        add_comments: bool = True,
    ):
        self.pen_up_cmd = pen_up_cmd
        self.pen_down_cmd = pen_down_cmd
        self.feed_rate = feed_rate
        self.rapid_rate = rapid_rate
        self.units = units
        self.add_comments = add_comments

        self.gcode: List[str] = []
        self.current_pos = Point(0, 0)
        self.pen_is_down = False

    def reset(self):
        """Clear generated G-code"""
        self.gcode = []
        self.current_pos = Point(0, 0)
        self.pen_is_down = False

    def comment(self, text: str):
        """Add a comment line"""
        if self.add_comments:
            self.gcode.append(f"; {text}")

    def header(self):
        """Add G-code header"""
        self.comment("Generated by Arduino CNC Suite")
        self.gcode.append("G21" if self.units == "mm" else "G20")  # Units
        self.comment("Set absolute positioning")
        self.gcode.append("G90")  # Absolute coordinates
        self.comment("Home machine")
        self.gcode.append("G28")
        self.pen_up()

    def footer(self):
        """Add G-code footer"""
        self.pen_up()
        self.comment("Return to home")
        self.gcode.append("G28")
        self.comment("Program end")
        self.gcode.append("M2")

    def pen_up(self):
        """Raise the pen"""
        if self.pen_is_down or not self.gcode:
            self.gcode.append(self.pen_up_cmd)
            self.pen_is_down = False

    def pen_down(self):
        """Lower the pen"""
        if not self.pen_is_down:
            self.gcode.append(self.pen_down_cmd)
            self.pen_is_down = True

    def rapid_move(self, x: float, y: float):
        """Rapid positioning (pen up, fast move)"""
        self.pen_up()
        self.gcode.append(f"G0 X{x:.3f} Y{y:.3f}")
        self.current_pos = Point(x, y)

    def linear_move(self, x: float, y: float, feed_rate: Optional[int] = None):
        """Linear interpolation (drawing move)"""
        if feed_rate is None:
            feed_rate = self.feed_rate
        self.gcode.append(f"G1 X{x:.3f} Y{y:.3f} F{feed_rate}")
        self.current_pos = Point(x, y)

    def draw_line(self, x1: float, y1: float, x2: float, y2: float):
        """Draw a line from (x1,y1) to (x2,y2)"""
        self.rapid_move(x1, y1)
        self.pen_down()
        self.linear_move(x2, y2)
        self.pen_up()

    def draw_polyline(self, points: List[Tuple[float, float]]):
        """Draw a connected series of lines"""
        if not points:
            return

        # Move to start
        self.rapid_move(points[0][0], points[0][1])
        self.pen_down()

        # Draw lines
        for x, y in points[1:]:
            self.linear_move(x, y)

        self.pen_up()

    def draw_rectangle(self, x: float, y: float, width: float, height: float):
        """Draw a rectangle"""
        points = [
            (x, y),
            (x + width, y),
            (x + width, y + height),
            (x, y + height),
            (x, y),  # Close the shape
        ]
        self.draw_polyline(points)

    def draw_circle(self, cx: float, cy: float, radius: float, segments: int = 36):
        """Draw a circle using line segments"""
        points = []
        for i in range(segments + 1):
            angle = (2 * math.pi * i) / segments
            x = cx + radius * math.cos(angle)
            y = cy + radius * math.sin(angle)
            points.append((x, y))
        self.draw_polyline(points)

    def get_gcode(self) -> List[str]:
        """Return the generated G-code as a list of strings"""
        return self.gcode

    def save(self, filepath: str):
        """Save G-code to file"""
        with open(filepath, "w") as f:
            f.write("\n".join(self.gcode))

    def __str__(self) -> str:
        """Return G-code as a single string"""
        return "\n".join(self.gcode)
